blank_issues_enabled: false
contact_links:
  - name: Support Center
    url: https://github.com/Snenjih/Support/issues
    about: Report any feature requests or bugs in the support center
  - name: Discord
    url: https://discord.gg/f46gXT69Fd
    about: Official Terminus Discord server for general discussion and quick support
